### PR TITLE
Added poetry + other fixes.

### PR DESCRIPTION
**Pull request by tyomo4ka**

### CODE REVIEW

**Comment by torchello** [comment]
# [Codecov](https://codecov.io/gh/tyomo4ka/django-reactive/pull/5?src=pr&el=h1) Report
> Merging [#5](https://codecov.io/gh/tyomo4ka/django-reactive/pull/5?src=pr&el=desc) into [master](https://codecov.io/gh/tyomo4ka/django-reactive/commit/9eb74e42bf27efb26274638ad22539f44bed5701&el=desc) will **not change** coverage by `%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/tyomo4ka/django-reactive/pull/5?src=pr&el=tree)

```diff
@@           Coverage Diff           @@
##           master       #5   +/-   ##
=======================================
  Coverage   82.97%   82.97%           
=======================================
  Files           5        5           
  Lines          47       47           
=======================================
  Hits           39       39           
  Misses          8        8           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/tyomo4ka/django-reactive/pull/5?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/tyomo4ka/django-reactive/pull/5?src=pr&el=footer). Last update [9eb74e4...29ccd61](https://codecov.io/gh/tyomo4ka/django-reactive/pull/5?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by tyomo4ka** [comment]
@torchello Hm, do you know why Travis sends coverage reports from your name? :)

**Comment by torchello** [comment]
@tyomo4ka not sure lol. have you found out why?

**Comment by tyomo4ka** [comment]
@torchello I don't know mate. But I don't trust Travis anymore. Revoked the access token will switch over to GH actions eventually.

**Pull request merged**
